name: Team Manage Resources
on:
  push:
    paths:
      - 'teams/**'
  workflow_dispatch:

jobs:
  team-resource-management:
    runs-on: ubuntu-latest
    environment: 
      name: cloud-platform

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML PyGithub gitpython

      - name: Maintain team repositories
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_ORGANIZATION: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_BEFORE: ${{ github.event.before }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          python .github/scripts/team_manage_resource.py
